imports:
    - { resource: config.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    csrf_protection: true

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: array
                query_cache_driver:    array

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        console:
            type:  console

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: false

pim_import_export:
    record_mails: true

parameters:
    max_products_category_removal: 20
    installer_data:       PimInstallerBundle:minimal
    archive_dir:          ''
    catalog_storage_dir:  ''
    tmp_storage_dir:      ''
    upload_dir:           '%kernel.root_dir%/uploads/product'
    upload_tmp_dir:       '%kernel.root_dir%/var/upload_tmp_dir'
