imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: false

parameters:
    max_products_category_removal: 20
    installer_data:       PimInstallerBundle:minimal
    archive_dir:          ''
    catalog_storage_dir:  ''
    tmp_storage_dir:      ''
    upload_dir:           '%kernel.root_dir%/uploads/product'
    upload_tmp_dir:       '%kernel.root_dir%/var/upload_tmp_dir'
